# Generated by Django 5.1.1 on 2024-09-21 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_appointment_status_availableday_timeslot'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('doctor', 'day')},
        ),
    ]
